spring:
  zipkin:
    baseUrl: http://zipkin.istio-system.svc:9411
    sender:
      type: web
  sleuth:
    opentracing:
      enabled: true
    baggage:
      correlation-enabled: true
      remote-fields: x-request-id, x-access-token
      correlation-fields: x-request-id

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState, livenessResponseCheck, kafka
        readiness:
          include: readinessState, db, kafka
    loggers:
      enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

probes:
  liveness:
    failureThreshold: 10

data-platform:
  kafka:
    consumer:
      enabled: true
      group-id: process-history-api
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      trusted-packages:
        - com.epam.digital.data.platform.bphistory.model
        - com.epam.digital.data.platform.bpm.history.base.dto
        - com.epam.digital.data.platform.bphistory.persistence.model
      custom-config:
        "[spring.deserializer.key.delegate.class]": org.apache.kafka.common.serialization.StringDeserializer
        "[spring.deserializer.value.delegate.class]": org.springframework.kafka.support.serializer.JsonDeserializer
        "[isolation.level]": read_committed
        "[enable.auto.commit]": false
    topics:
      bpm-history-process: bpm-history-process
      bpm-history-task: bpm-history-task