spring:
  zipkin:
    enabled: false
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
  autoconfigure:
    exclude: com.epam.digital.data.platform.starter.database.DatabaseAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update

data-platform:
  kafka:
    bootstrap: localhost:9092
    ssl:
      enabled: false

audit:
  kafka:
    bootstrap: localhost:9092
    topic: audit-events
    schema-registry-url: http://localhost:8081
    ssl:
      enabled: false